owner: Barctic
repo: gnwt-monitor

sites:
  - name: GNWT Main Page
    url: https://www.gov.nt.ca
    
  - name: Education Culture and Employment
    url: https://www.ece.gov.nt.ca
  - name: Environment and Natural Resources
    url: https://www.enr.gov.nt.ca
  - name: Executive and Indigenous Affairs
    url: https://www.eia.gov.nt.ca
  - name: Finance
    url: https://www.fin.gov.nt.ca
  - name: Health and Social Services
    url: https://www.hss.gov.nt.ca
  - name: Industry, Tourism and Investment
    url: https://www.iti.gov.nt.ca
  - name: Infrastructure
    url: https://www.inf.gov.nt.ca
  - name: Justice
    url: https://www.justice.gov.nt.ca
  - name: Lands
    url: https://www.lands.gov.nt.ca
  - name: Legislative Assembly
    url: https://www.ntassembly.ca
  - name: Municipal and Community Affairs
    url: https://www.maca.gov.nt.ca
    
  - name: Aurora College
    url: https://www.auroracollege.nt.ca
  - name: NWT Business Development and Investment Corporation
    url: https://www.bdic.ca
  - name: Health and Social Services Authority
    url: https://www.nthssa.ca
  - name: Hay River Health and Social Services Authority 
    url: https://www.hrhssa.org/
  - name: NWT Housing Corporation
    url: https://www.nwthc.gov.nt.ca
  - name: Northwest Territories Liquor and Cannabis Commission
    url: https://www.ntlcc.ca
  - name: Northwest Territories Power Corporation
    url: https://www.ntpc.com/
  - name: Tlicho Community Services Agency
    url: https://www.tlicho.ca/agencies/tlicho-community-services-agency
  - name: Workers Safety and Compensation Commission
    url: https://www.wscc.nt.ca

status-website:
  baseUrl: /gnwt-monitor
  logoUrl: https://raw.githubusercontent.com/Barctic/gnwt-monitor/master/assets/barctic-avatar-for-monitor.svg
  name: GNWT Website Status Monitor
  introTitle: "**GNWT Website Monitor** uptime and performance monitoring."
  introMessage: Created by [Barctic Techology "Barctic Techology - Yellowknife"](https://barctic.com/?utm_source=gnwt-monitor).
  navbar:
    - title: Status
      href: /
    - title: Barctic Technology
      href: https://barctic.com/?utm_source=gnwt-monitor

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
